export PATH="$PATH:/usr/local/mysql/bin"
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/usr/local/mysql/lib/"
#export VERSIONER_PYTHON_PREFER_64_BIT=no
#export VERSIONER_PYTHON_PREFER_32_BIT=yes
export PS1="[\u:\W]$ "
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
alias mvim='/Applications/MacVim.app/Contents/MacOS/Vim -g'
alias server='open http://localhost:8080 && python -m SimpleHTTPServer 8080'